### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by dmckminard** [skiselev/i2s_audio_phat#1]
Hello !
I mounted the phat i2s audio card, and I have some concerns. It is correctly recognized by debian, but impossible to have sound. Do you know where it can come from?
I am on debian stretch.

**Comment by skiselev** [comment]
Hi,

It is possible that the mixer is muted. In this case the WM8731 won't even accept the data for the playback. Please check the mixer settings, unmute if needed.
I think the following commands should do it:
`amixer set 'Master' 80 unmute`
`amixer set 'Output Mixer HiFi' unmute`

 If that still doesn't work, please send me the output of `amixer contents`

Thanks!

**Comment by dmckminard** [comment]
I've done this and still no sound.

Please see below the output of amixer contents:

> numid=2,iface=MIXER,name='Master Playback ZC Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=off,off
numid=1,iface=MIXER,name='Master Playback Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=127,step=0
  : values=127,127
  | dBscale-min=-121.00dB,step=1.00dB,mute=1
numid=4,iface=MIXER,name='Line Capture Switch'
  ; type=BOOLEAN,access=rw------,values=2
  : values=off,off
numid=5,iface=MIXER,name='Mic Boost Volume'
  ; type=INTEGER,access=rw---R--,values=1,min=0,max=1,step=0
  : values=0
  | dBscale-min=0.00dB,step=20.00dB,mute=0
numid=6,iface=MIXER,name='Mic Capture Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
numid=8,iface=MIXER,name='ADC High Pass Filter Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=3,iface=MIXER,name='Capture Volume'
  ; type=INTEGER,access=rw---R--,values=2,min=0,max=31,step=0
  : values=31,31
  | dBscale-min=-34.50dB,step=1.50dB,mute=0
numid=10,iface=MIXER,name='Playback Deemphasis Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
numid=14,iface=MIXER,name='Input Mux'
  ; type=ENUMERATED,access=rw------,values=1,items=2
  ; Item #0 'Line In'
  ; Item #1 'Mic'
  : values=0
numid=13,iface=MIXER,name='Output Mixer HiFi Playback Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
numid=11,iface=MIXER,name='Output Mixer Line Bypass Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
numid=12,iface=MIXER,name='Output Mixer Mic Sidetone Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
numid=7,iface=MIXER,name='Sidetone Playback Volume'
  ; type=INTEGER,access=rw---R--,values=1,min=0,max=3,step=0
  : values=3
  | dBscale-min=-15.00dB,step=3.00dB,mute=0
numid=9,iface=MIXER,name='Store DC Offset Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off

Thanks to you for your reply!

**Comment by skiselev** [comment]
The mixer settings look good to me. My only other guess would be that the sound is being output elsewhere, for example to the built-in RPi BCM audio.
Can you please provide the output of
`aplay -l`
And also the command you're using to play the audio.
I'll try to reproduce the issue locally. It might take some time though.

**Comment by dmckminard** [comment]
Of course : 

> **** List of PLAYBACK Hardware Devices ****
> card 0: sndrpiproto [snd_rpi_proto], device 0: WM8731 HiFi wm8731-hifi-0 []
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0

I've used using speaker-test -c2 -D default:CARD=sndrpiproto, aplay test.wav (with a wav file), and aplay -D default:CARD=sndrpiproto (specifying the device)

**Comment by skiselev** [comment]
I've tested my pHAT with the current release of Raspbian Stretch, dated 2019-04-08, and it works just fine.
I'd recommend checking the LHPOUT (#9) and RHPOUT (#10) output pins on WM8731 with an oscilloscope. Or checking that coupling capacitors C22 and C23 are connected correctly.
You might also want to check the signal on Line Output jack.

**Comment by dmckminard** [comment]
Ok I'm going to check that so. But I have some doubts about the fact that it comes from an electronic problem on my side, because I developed 2 cards like yours and neither of them works.
Just to be sure, you can configure the card via the Raspbian Configuration part, or via the Raspberry Pi HAT ID EEPROM Programming part. The latter is not essential, and I can very well only go through the steps described in Raspbian Configuration?

**Comment by skiselev** [comment]
Can you please try removing or commenting out the following line from your /boot/config.txt:
`dtoverlay=i2s-mmap`
It seems that it is not needed on Raspbian Stretch.

**Comment by skiselev** [comment]
Can you please confirm if the configuration change above fixes the issue?

**Comment by dmckminard** [comment]
Oh sorry I've forget to answer! No still no sound, and all our parts seems to be connected correctly

**Comment by skiselev** [comment]
Weird. Do you have an oscilloscope to check the I2S signals and audio output signals?

**Comment by dmckminard** [comment]
Yes, all seems good

**Comment by dmckminard** [comment]
Yes, you were right! My problems comes from hardware. I've baked a new card and it's working nice, thanks !
