### ISSUE TITLE
missing my_components

### ISSUE THREAD

**Issue by hemna** [skiselev/i2s_audio_phat#2]
Do you happen to have the 'my_components' library?

I'm trying to use your repo as a basis for building a cm4 carrier board that will use this audio schematic and kicad is complaining about missing my_components library.   I'm on macos btw.

**Comment by skiselev** [comment]
It should be here: https://github.com/skiselev/my_kicad_library, although that library is pretty much work in progress, so it might not match whatever is in the I2S Audio pHAT
